# Геометрия резервуара и сетка
dx: 0.02
width: 1.0
height: 0.5
init_height: 0.25   # высота столба воды
h: 0.026            # сглаживающая длина (≈1.3·dx)

# Гравитация и число слоёв стенок
g: 9.81
wall_layers: 2

# Дамп .xyz каждые N шагов
dump_step: 10

# Границы области для отражения (xmin, ymin) – (xmax, ymax)
domain_bounds:
  - [0.0, 0.0]
  - [1.0, 0.5]

# Хотим ядро Wendland C2 (устойчивее к pairing)
kernel: wendlandC2
