# Параметры «вода»
rho0: 1000.0          # базовая плотность (кг/м³)
c0: 15.0              # скорость звука в воде (перекроет common.c0)

# Включаем технику сдвига частиц (XSPH Монaгана)
pst: monaghan
pst_kwargs:
  eps: 0.6            # коэффициент XSPH ε
