# Общий файл конфигурации (обязательный)
profile: 'water'
scenario: 'square_drop'
kernel: 'wendland'
pst: "oger"
viscosity: "artificial"

# Корректор (mls/shepard/none)
corrector: "none"
corrector_iter: 1
corrector_period: 10

# Поиск соседей (bruteforce, cell_linked, kd_tree)
neighbor_method: "cell_linked"
qmax: 1.9

# Общие численные параметры
gamma: 7.0            # показатель адиабаты в EOS

# Расчёт тепла
solve_heat: False

# Шаг времени и суммарное время моделирования
dt: 0.001
total_time: 0.1

# Параметры визуализации
xyz_save: True
dump_period: 1
