# Общий файл конфигурации (обязательный)
profile: 'water'
scenario: 'eos_test'
kernel: 'wendland'
pst: "monaghan"
viscosity: "artificial"
neighbor_method: "bruteforce"

# Корректор (mls/shepard/none)
corrector: "shepard"
corrector_iter: 1
corrector_period: 1

# Общие численные параметры
gamma: 7.0            # показатель адиабаты в EOS
epsilon: 0.01         # ε в формуле μ_ij

# Шаг времени и суммарное время моделирования
dt: 0.001
total_time: 2.0
