# Общий файл конфигурации (обязательный)
profile: 'water'
scenario: 'square_drop'

# Общие численные параметры
gamma: 7.0            # показатель адиабаты в EOS
c0: 20.0              # характерная скорость звука (м/с)
alpha: 1.0            # искусственная вязкость Monaghan α
beta: 2.0             # искусственная вязкость Monaghan β
epsilon: 0.01         # ε в формуле μ_ij

# Шаг времени и суммарное время моделирования
dt: 0.001
total_time: 2.0

# Метод поиска соседей по умолчанию
neighbor_method: kd_tree
